src/apps/news/urls.py
# Django
from django.urls import path

# Views
from apps.news import views


app_name = 'news'

urlpatterns = [
    path(
        'noticia/<slug:slug>/',
        views.NewsDetail.as_view(),
        name='detail_news'
    ),
    path(
        'panel/noticias/',
        views.NewsPnlList.as_view(),
        name='admin_news_list'
    ),
    path(
        'panel/noticia/nueva/',
        views.NewsCreate.as_view(),
        name='create_news'
    ),
    path(
        'panel/noticia/editar/<slug:slug>/',
        views.NewsUpdate.as_view(),
        name='update_news'
    ),
    path(
        'panel/noticia/eliminar/<int:pk>/',
        views.NewsDelete.as_view(),
        name='delete_news'
    ),
    path(
        'panel/imagen/eliminar/<int:pk>/<slug:slug>/',
        views.ImageDelete.as_view(),
        name='delete_image'
    ),
    path(
        'panel/categorias/',
        views.CategoryList.as_view(),
        name='list_categories'
    ),
    path(
        'panel/categoria/nueva/',
        views.CategoryCreate.as_view(),
        name='create_category'
    ),
    path(
        'panel/categoria/editar/<slug:slug>/',
        views.CategoryUpdate.as_view(),
        name='update_category'
    ),
    path(
        'panel/categoria/eliminar/<slug:slug>/',
        views.CategoryDelete.as_view(),
        name='delete_category'
    ),
    path(
        'panel/autores/',
        views.AuthorList.as_view(),
        name='list_authors'
    ),
    path(
        'panel/autor/nuevo/',
        views.AuthorCreate.as_view(),
        name='create_author'
    ),
    path(
        'panel/autor/editar/<slug:slug>/',
        views.AuthorUpdate.as_view(),
        name='update_author'
    ),
    path(
        'panel/autor/eliminar/<slug:slug>/',
        views.AuthorDelete.as_view(),
        name='delete_author'
    ),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.www.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.news.urls')),
    path('admin/', admin.site.urls),
    path('froala_editor/',include('froala_editor.urls')),
]

# Media Url
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/news/models.py
import os
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Category(models.Model):

	name = models.CharField('Nombre', max_length=120, unique=True)
	slug = models.SlugField(max_length=120, unique=True, editable=False)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)


class Author(models.Model):

	first_name = models.CharField('Nombre(s)', max_length=120)
	last_name = models.CharField('Apellido(s)', max_length=120, null=True, blank=True)
	email = models.EmailField('Email', blank=True, null=True)
	slug = models.SlugField(max_length=120, unique=True, editable=False)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

	def save(self, *args, **kwargs):
		self.slug = slugify(f'{self.first_name} {self.last_name}')
		super(Author, self).save(*args, **kwargs)


class News(models.Model):

	title = models.CharField('Título de la noticia *', max_length=120, unique=True)
	slug = models.SlugField(max_length=120, unique=True, editable=False)
	body = models.TextField('Contenido de la noticia *')
	cover = models.ImageField(upload_to='cover', blank=True, null=True)
	video = models.URLField('URL video youtube', blank=True, null=True)	
	category = models.ForeignKey(
		Category,
		on_delete=models.CASCADE,
		related_name='news',
		verbose_name='Categoría *'
	)
	author = models.ForeignKey(
		Author,
		on_delete=models.CASCADE,
		related_name='news',
		verbose_name='Autor *'
	)
	views = models.IntegerField(default=0)
	published = models.BooleanField(default=True)
	date_published = models.DateTimeField(blank=True, null=True)
	is_task = models.BooleanField('Programar publicación', default=False)
	date_task = models.DateField('Día', blank=True, null=True)
	hour_task = models.TimeField('Hora', blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(News, self).save(*args, **kwargs)

	class Meta:
		ordering = ["-date_published"]


class Gallery(models.Model):

	image = models.ImageField(upload_to='noticias')
	news =  models.ForeignKey(News, related_name='gallery', on_delete=models.CASCADE)

	def delete(self, *args, **kwargs):
		self.image.delete(save=True)
		super(Gallery, self).delete(*args, **kwargs)

src/apps/news/forms/author.py
# Django
from django import forms

# Models
from apps.news.models import Author


class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = '__all__'

src/apps/news/forms/category.py
# Django
from django import forms

# Models
from apps.news.models import Category


class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = '__all__'

src/apps/news/forms/news.py
# -*- coding: utf-8 -*-
from django import forms
from froala_editor.widgets import FroalaEditor

from apps.news.models import News


class NewsForm(forms.ModelForm):
	body = forms.CharField(widget=FroalaEditor)
	images = forms.ImageField(
		label='Imagenes *',
		widget=forms.ClearableFileInput(
			attrs={'allow_multiple_selected': True}
		)
	)
	class Meta:
		model = News
		fields = [
			'title', 'body', 'author', 'category',
			'video', 'is_task', 'date_task', 'hour_task'
		]
		widgets = {
			'date_task': forms.TextInput(attrs={'type': 'date'}),
			'hour_task': forms.TimeInput(attrs={'type': 'time'}),
		}

	def __init__(self, *args, **kwargs):
		super(NewsForm, self).__init__(*args, **kwargs)
		self.fields['images'].widget.attrs.update({'accept': 'image/*', 'multiple': 'multiple'})


class NewsUpdateForm(NewsForm):
	images = forms.ImageField(
		label='Imagenes',
		required=False, 
		widget=forms.ClearableFileInput(
			attrs={'allow_multiple_selected': True}
		)
	)

src/apps/news/views/author.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

# Models
from apps.news.models import Author

# Form
from apps.news.forms import AuthorForm


class AuthorList(LoginRequiredMixin, ListView):
	context_object_name = 'authors'
	queryset = Author.objects.all()
	template_name = 'author/list.html'


class AuthorCreate(LoginRequiredMixin, CreateView):
	form_class = AuthorForm
	success_url = reverse_lazy('news:list_authors')
	template_name = 'author/create_update.html'


class AuthorUpdate(LoginRequiredMixin, UpdateView):
	form_class = AuthorForm
	model = Author
	success_url = reverse_lazy('news:list_authors')
	template_name = 'author/create_update.html'


class AuthorDelete(LoginRequiredMixin, DeleteView):
	model = Author
	template_name = 'author/delete.html'
	success_url = reverse_lazy('news:list_authors')

src/apps/news/views/category.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

# Models
from apps.news.models import Category

# Form
from apps.news.forms import CategoryForm


class CategoryList(LoginRequiredMixin, ListView):
	context_object_name = 'categories'
	queryset = Category.objects.all()
	template_name = 'category/list.html'


class CategoryCreate(LoginRequiredMixin, CreateView):
	form_class = CategoryForm
	success_url = reverse_lazy('news:list_categories')
	template_name = 'category/create_update.html'


class CategoryUpdate(LoginRequiredMixin, UpdateView):
	form_class = CategoryForm
	model = Category
	success_url = reverse_lazy('news:list_categories')
	template_name = 'category/create_update.html'


class CategoryDelete(LoginRequiredMixin, DeleteView):
	model = Category
	template_name = 'category/delete.html'
	success_url = reverse_lazy('news:list_categories')

src/apps/news/views/news.py
import datetime

# Django
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import DeletionMixin

# Models
from apps.news.models import News, Gallery

# Form
from apps.news.forms import NewsForm, NewsUpdateForm


class NewsDetail(DetailView):
	model = News
	template_name = 'news/detail.html'


class NewsPnlList(LoginRequiredMixin, ListView):
	context_object_name = 'news'
	queryset = News.objects.filter(published=True).order_by('-date_published')
	template_name = 'news/admin_list.html'
	login_url = reverse_lazy('user:login')
	permission_required = "news.add_news"
	paginate_by = 10

	def get_context_data(self, **kwargs):
		context = super(NewsPnlList, self).get_context_data(**kwargs)
		context['news_inactive'] = News.objects.filter(published=False, is_task=False).order_by('-date_published')
		context['news_tasks'] = News.objects.filter(published=False, is_task=True).order_by('-date_published')
		context['total'] = News.objects.filter(published=True).order_by('-date_published').count()
		return context


class NewsCreate(LoginRequiredMixin, CreateView):
	form_class = NewsForm
	success_url = reverse_lazy('news:admin_news_list')
	template_name = 'news/create.html'
	login_url = reverse_lazy('user:login')
	permission_required = "news.add_news"

	def form_valid(self, form):
		self.object = form.save()
		self.object.date_published = datetime.datetime.now()
		images = self.request.FILES.getlist('images')
		for image in images:
			Gallery.objects.create(image=image, news=self.object)
		cover = self.object.gallery.first()
		self.object.cover = cover.image
		return super(NewsCreate, self).form_valid(form)


class NewsUpdate(LoginRequiredMixin, UpdateView):
	form_class = NewsUpdateForm
	model = News
	success_url = reverse_lazy('news:admin_news_list')
	template_name = 'news/update.html'
	login_url = reverse_lazy('user:login')
	permission_required = "news.change_news"

	def form_valid(self, form):
		self.object = form.save()
		images = self.request.FILES.getlist('images')
		for image in images:
			Gallery.objects.create(image=image, news=self.object)
		return super(NewsUpdate, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(NewsUpdate, self).get_context_data(**kwargs)
		images = Gallery.objects.filter(news=self.object)
		cover = images.first()
		self.object.cover = cover.image
		self.object.save()
		context['is_published'] = self.object.published
		context['gallery'] = images
		context['slug_news'] = self.object.slug
		return context


class NewsDelete(LoginRequiredMixin, DeleteView):
	model = News
	template_name = 'news/delete.html'
	success_url = reverse_lazy('news:admin_news_list')


class ImageDelete(DeletionMixin, SingleObjectMixin, View):
	login_url = reverse_lazy('user:login')
	model = Gallery
	permission_required = "news.delete_news"
	pk_url_kwarg = "pk"

	def get(self, *args, **kwargs):
		return self.delete(*args, **kwargs)

	def get_success_url(self):
		return reverse_lazy('news:update_news', kwargs={'slug':self.kwargs.get('slug')})

src/apps/news/templates/category/create_update.html
{% extends "base.html" %}

{% block title %}Gestión de Categoría{% endblock title %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="gral__forms matchHeight">
      <h1>Gestión de Categoría</h1>
      <form method="post" class="form__gral">
        {% csrf_token %}
        <div class="field">
          {{ form.name.label_tag }}
          {{ form.name }}
          {{ form.name.errors }}
        </div>
        <div class="field">
          <button type="submit" class="btn">Guardar</button>
          <a href="{% url 'news:list_categories' %}" class="btn">Cancelar</a>
        </div>
      </form>
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main> 
{% endblock content %}

src/apps/news/templates/category/delete.html
{% extends "base.html" %}

{% load static %}

{% block title %}Eliminar categoría{% endblock title %}

{% block css %}
<link href="{% static 'css/noticias.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="gral__forms matchHeight">
      <h1>Eliminar la Categoría</h1>
      <form method="post" class="form__gral">
        {% csrf_token %}
        <p>¿Estás seguro de que deseas eliminar la categoría "{{ object.name }}"?</p>
        <div class="field">
          <button type="submit" class="btn">Eliminar</button>
          <a href="{% url 'news:list_categories' %}" class="btn">Cancelar</a>
        </div>
      </form>
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main>
{% endblock %}

src/apps/news/templates/category/list.html
{% extends "base.html" %}

{% block title %}Lista de Categorias{% endblock title %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="panel matchHeight">
      <div class="pnl__hdr">
        <p class="pnl__hdr__info">Hay {{ categories.count }} categorías</p>
        <p class="pnl__hdr__btn"><a href="{% url 'news:create_category' %}" class="btn">Crear Categoría</a></p>
      </div>
      <div class="pnl__table">
        <table class="tbl__rd__gral">
          <thead>
            <tr><th colspan="2">Categorías</th></tr>
          </thead>
          <tbody>
          {% for category in categories %}            
            <tr>
              <td class="organisation__cat">{{ category.name }}</td>
              <td class="actions__gral_one">
                <a href="{% url 'news:update_category' category.slug %}" class="tbl__actions">Editar</a> | 
                <a href="{% url 'news:delete_category' category.slug %}" class="tbl__actions">Eliminar</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main>
{% endblock content %}