src/apps/news/urls.py
# Django
from django.urls import path

# Views
from apps.news import views


app_name = 'news'

urlpatterns = [
    path(
        'noticia/<slug:slug>/',
        views.NewsDetail.as_view(),
        name='detail_news'
    ),
    path(
        'panel/noticias/',
        views.NewsPnlList.as_view(),
        name='admin_news_list'
    ),
    path(
        'panel/noticia/nueva/',
        views.NewsCreate.as_view(),
        name='create_news'
    ),
    path(
        'panel/noticia/editar/<slug:slug>/',
        views.NewsUpdate.as_view(),
        name='update_news'
    ),
    path(
        'panel/noticia/eliminar/<int:pk>/',
        views.NewsDelete.as_view(),
        name='delete_news'
    ),
    path(
        'panel/imagen/eliminar/<int:pk>/<slug:slug>/',
        views.ImageDelete.as_view(),
        name='delete_image'
    ),
    path(
        'panel/categorias/',
        views.CategoryList.as_view(),
        name='list_categories'
    ),
    path(
        'panel/categoria/nueva/',
        views.CategoryCreate.as_view(),
        name='create_category'
    ),
    path(
        'panel/categoria/editar/<slug:slug>/',
        views.CategoryUpdate.as_view(),
        name='update_category'
    ),
    path(
        'panel/categoria/eliminar/<slug:slug>/',
        views.CategoryDelete.as_view(),
        name='delete_category'
    ),
    path(
        'panel/autores/',
        views.AuthorList.as_view(),
        name='list_authors'
    ),
    path(
        'panel/autor/nuevo/',
        views.AuthorCreate.as_view(),
        name='create_author'
    ),
    path(
        'panel/autor/editar/<slug:slug>/',
        views.AuthorUpdate.as_view(),
        name='update_author'
    ),
    path(
        'panel/autor/eliminar/<slug:slug>/',
        views.AuthorDelete.as_view(),
        name='delete_author'
    ),
]

src/apps/users/urls.py
# Django
from django.urls import path

# Views
from apps.users import views

app_name = 'user'


urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

src/apps/www/urls.py
# Django
from django.urls import path

# Views
from apps.www import views


app_name = 'site'

urlpatterns = [
    path('', views.index, name='index'),
    path('celery/', views.testing_celery, name='testing'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.www.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.news.urls')),
    path('admin/', admin.site.urls),
    path('froala_editor/',include('froala_editor.urls')),
]

# Media Url
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/_layouts/footer.html
<footer>
	<div class="container">
		<p>
			Sensor Informativo, todos los derechos reservados 
			<span style="float: right;">No. de Visitas: 0</span>
		</p>
		<p> Realizado por: <a href="http://kushiahu.github.io/" style="color:#f88535" target="_blank">Josue Tamayo</a></p>
	</div>
</footer>

src/templates/_layouts/header.html
{% load static %}
<header>
  <section class="hdr__top">
    <div class="container">
      <nav class="hdr__top__nav">
        <ul class="hdr__top__list">
          <li><a href="https://www.facebook.com/SensorInformativo" target="_blank"><span class="icon-facebook"></span></a></li>
          <li><a href="https://www.twitter.com/SensorInformati" target="_blank"><span class="icon-twitter"></span></a></li>
          <li><a href="https://plus.google.com/u/0/102036881259537589669/" target="_blank"><span class="icon-google-plus"></span></a></li>
          <li><a href="https://www.youtube.com" target="_blank"><span class="icon-youtube"></span></a></li>
        </ul>
      </nav>
      <nav class="hdr__top__login">
        <ul class="hdr__top__list">
          {% if user.is_authenticated %}
          <li><a href="{% url 'user:logout' %}"><i class="icon-user"></i>Salir</a></li>
          {% else %}
            <li><a href="{% url 'user:login' %}"><i class="icon-user"></i>Login</a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
  </section>
  <section class="hdr__sensor">
    <div class="container">
      <section class="hdr__logo"><figure><a href="{% url 'site:index' %}"><img src="{% static 'images/logo.png' %}"></a></figure></section>
      <section class="hdr__sponsor">
        <div id="hdr__sponsor">
          <div>
            <a href="#">
              <img src="{% static 'images/pc.png' %}" alt="Imagen: Tu espacio de publicidad">
            </a>
          </div> 
        </div>
      </section>
      <section class="hdr__weather">
        <p class="hdr__wi"><i class="wi"></i></p>
        <p>Temp. 30C</p> 
        <p>{{w.description}}</p> 
      </section>
    </div>
  </section>
  {% include '_layouts/nav.html' %}
</header>

src/templates/_layouts/nav.html
<nav class="hdr__navbar">
  <div class="container">
    <div class="toggle"><a href="#" class="toggleMenu">Menu</a></div>
    <ul class="nav">
      <li><a href="/">Inicio</a></li>
      <li>
        <a href="#">Secciones</a>				
        <ul>
          <li><a href="#">Todos</a></li>        
          <li><a href="#">Categoría</a></li>	
        </ul>
      </li>
      <li><a href="#">Columnas</a></li>
      <li><a href="#">Clasificados</a></li>
      <li><a href="#">Bolsa de Trabajo</a></li>
      <li><a href="#" class="the__last">Contacto</a></li> 
      <li><a href="#" class="the__last the__login">Registrate</a></li>
    </ul>
  </div>
</nav>

src/templates/_layouts/pagination.html
<section class="list_pagination">
  <ul class="pagination">
  {% if page_obj.has_previous %}
    <li><a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; anterior</a></li>
  {% else %}
    <li><a class="prev disabled">&lsaquo;&lsaquo; anterior</a></li>   
  {% endif %}

  {% for page in page_obj.pages %}
    {% if page %}
      {% ifequal page page_obj.number %}
    <li><a href="#" class="active">{{ page }}</a></li>
      {% else %}
    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
      {% endifequal %}
    {% else %}  
    <li class="disabled"><a href="#">...</a></li>  
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <li><a href="?{{ page_obj.next_page_number.querystring }}" class="next">siguiente &rsaquo;&rsaquo;</a></li>
  {% else %}
    <li><a class="next disabled">siguiente &rsaquo;&rsaquo;</a></li>
  {% endif %}
  </ul>
</section>

src/templates/_layouts/pnl_sponsors.html
<sidebar class="main__sponsors matchHeight">
  <h2>Mi panel ( <a href="#" class="pnl__logout">salir</a> )</h2>
  <div class="panel__user">
    <!-- Falta realizar un if -->
    <figure class="pnl__user__img"><img src="#" alt="Photo: {{user.username}}" class="rounded"></figure>  
    <p class="pnl__user__name">{{ user.first_name }} {{ user.last_name }}</p>
    <p class="pnl__user__rol"><a href="#" style="color:#454545;">Editar Perfil</a></p>
    <ul class="pnl__user__menu">
    {% if user.is_superuser %}      
      <li>
        <a href="#">Noticias</a>
        <a href="{% url 'news:list_categories' %}" class="pnl__menu__cat">Categorías</a>
        <a href="{% url 'news:list_authors' %}" class="pnl__menu__cat">Autores</a>
      </li>
      <li><a href="#">Columnas</a></li>
      <li>
        <a href="#">Publicidad</a>
        <a href="#" class="pnl__menu__cat">Empresas</a>
      </li>
    {% endif %}
      <li>
      {% if user.is_superuser %}
      <a href="#">Clasificados</a>
      <a href="#" class="pnl__menu__cat">Mis Clasificados</a>
      <a href="#" class="pnl__menu__cat">Categorías</a>
      {% else %}
      <a href="#">Clasificados</a>
      {% endif %}</li>
      <li>
        {% if user.is_superuser %}
        <a href="#">Empleos</a>
        <a href="#" class="pnl__menu__cat">Mis Empleos</a>
        <a href="#" class="pnl__menu__cat">Categorías</a>
        {% else %}
        <a href="#">Empleos</a>
        {% endif %}</li>
      {% if user.is_superuser %}
      <li><a href="#">Bandeja de Entrada</a></li>
      <li><a href="#">Suscriptores</a></li>
      <li><a href="#" style="color:#9E1A1A;">Eliminar por años</a></li>
      {% endif %}
    </ul>
  </div>
  <br><br><br><br>
</sidebar>

src/templates/_layouts/sponsors.html
{% load static %}

<sidebar class="main__sponsors matchHeight" id="main__sponsors">
	<h2>Publicidad</h2>
	<div class="main__sponsor__cnt">
		<a href="#" target="_blank">
      <img src="#" alt="Alt de la imagen">
		</a>
	</div>
	<div class="sponsor__get">
		<p>No esperes mas</p><a href="#" class="btn">Anunciate</a>
	</div>
</sidebar>