src/apps/news/urls.py
# Django
from django.urls import path

# Views
from apps.news import views


app_name = 'news'

urlpatterns = [
    path(
        'noticia/<slug:slug>/',
        views.NewsDetail.as_view(),
        name='detail_news'
    ),
    path(
        'panel/noticias/',
        views.NewsPnlList.as_view(),
        name='admin_news_list'
    ),
    path(
        'panel/noticia/nueva/',
        views.NewsCreate.as_view(),
        name='create_news'
    ),
    path(
        'panel/noticia/editar/<slug:slug>/',
        views.NewsUpdate.as_view(),
        name='update_news'
    ),
    path(
        'panel/noticia/eliminar/<int:pk>/',
        views.NewsDelete.as_view(),
        name='delete_news'
    ),
    path(
        'panel/imagen/eliminar/<int:pk>/<slug:slug>/',
        views.ImageDelete.as_view(),
        name='delete_image'
    ),
    path(
        'panel/categorias/',
        views.CategoryList.as_view(),
        name='list_categories'
    ),
    path(
        'panel/categoria/nueva/',
        views.CategoryCreate.as_view(),
        name='create_category'
    ),
    path(
        'panel/categoria/editar/<slug:slug>/',
        views.CategoryUpdate.as_view(),
        name='update_category'
    ),
    path(
        'panel/categoria/eliminar/<slug:slug>/',
        views.CategoryDelete.as_view(),
        name='delete_category'
    ),
    path(
        'panel/autores/',
        views.AuthorList.as_view(),
        name='list_authors'
    ),
    path(
        'panel/autor/nuevo/',
        views.AuthorCreate.as_view(),
        name='create_author'
    ),
    path(
        'panel/autor/editar/<slug:slug>/',
        views.AuthorUpdate.as_view(),
        name='update_author'
    ),
    path(
        'panel/autor/eliminar/<slug:slug>/',
        views.AuthorDelete.as_view(),
        name='delete_author'
    ),
]

src/apps/users/urls.py
# Django
from django.urls import path

# Views
from apps.users import views

app_name = 'user'


urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('apps.www.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.news.urls')),
    path('admin/', admin.site.urls),
    path('froala_editor/',include('froala_editor.urls')),
]

# Media Url
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/news/models.py
import os
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Category(models.Model):

	name = models.CharField('Nombre', max_length=120, unique=True)
	slug = models.SlugField(max_length=120, unique=True, editable=False)

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(Category, self).save(*args, **kwargs)


class Author(models.Model):

	first_name = models.CharField('Nombre(s)', max_length=120)
	last_name = models.CharField('Apellido(s)', max_length=120, null=True, blank=True)
	email = models.EmailField('Email', blank=True, null=True)
	slug = models.SlugField(max_length=120, unique=True, editable=False)

	def __str__(self):
		return f'{self.first_name} {self.last_name}'

	def save(self, *args, **kwargs):
		self.slug = slugify(f'{self.first_name} {self.last_name}')
		super(Author, self).save(*args, **kwargs)


class News(models.Model):

	title = models.CharField('Título de la noticia *', max_length=120, unique=True)
	slug = models.SlugField(max_length=120, unique=True, editable=False)
	body = models.TextField('Contenido de la noticia *')
	cover = models.ImageField(upload_to='cover', blank=True, null=True)
	video = models.URLField('URL video youtube', blank=True, null=True)	
	category = models.ForeignKey(
		Category,
		on_delete=models.CASCADE,
		related_name='news',
		verbose_name='Categoría *'
	)
	author = models.ForeignKey(
		Author,
		on_delete=models.CASCADE,
		related_name='news',
		verbose_name='Autor *'
	)
	views = models.IntegerField(default=0)
	published = models.BooleanField(default=True)
	date_published = models.DateTimeField(blank=True, null=True)
	is_task = models.BooleanField('Programar publicación', default=False)
	date_task = models.DateField('Día', blank=True, null=True)
	hour_task = models.TimeField('Hora', blank=True, null=True)
	created = models.DateTimeField(auto_now_add=True)
	modified = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(News, self).save(*args, **kwargs)

	class Meta:
		ordering = ["-date_published"]


class Gallery(models.Model):

	image = models.ImageField(upload_to='noticias')
	news =  models.ForeignKey(News, related_name='gallery', on_delete=models.CASCADE)

	def delete(self, *args, **kwargs):
		self.image.delete(save=True)
		super(Gallery, self).delete(*args, **kwargs)

src/apps/news/forms/author.py
# Django
from django import forms

# Models
from apps.news.models import Author


class AuthorForm(forms.ModelForm):
	class Meta:
		model = Author
		fields = '__all__'

src/apps/news/forms/category.py
# Django
from django import forms

# Models
from apps.news.models import Category


class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = '__all__'

src/apps/news/forms/news.py
# -*- coding: utf-8 -*-
from django import forms
from froala_editor.widgets import FroalaEditor

from apps.news.models import News


class NewsForm(forms.ModelForm):
	body = forms.CharField(widget=FroalaEditor)
	images = forms.ImageField(
		label='Imagenes *',
		widget=forms.ClearableFileInput(
			attrs={'allow_multiple_selected': True}
		)
	)
	class Meta:
		model = News
		fields = [
			'title', 'body', 'author', 'category',
			'video', 'is_task', 'date_task', 'hour_task'
		]
		widgets = {
			'date_task': forms.TextInput(attrs={'type': 'date'}),
			'hour_task': forms.TimeInput(attrs={'type': 'time'}),
		}

	def __init__(self, *args, **kwargs):
		super(NewsForm, self).__init__(*args, **kwargs)
		self.fields['images'].widget.attrs.update({'accept': 'image/*', 'multiple': 'multiple'})


class NewsUpdateForm(NewsForm):
	images = forms.ImageField(
		label='Imagenes',
		required=False, 
		widget=forms.ClearableFileInput(
			attrs={'allow_multiple_selected': True}
		)
	)

src/apps/news/views/author.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

# Models
from apps.news.models import Author

# Form
from apps.news.forms import AuthorForm


class AuthorList(LoginRequiredMixin, ListView):
	context_object_name = 'authors'
	queryset = Author.objects.all()
	template_name = 'author/list.html'


class AuthorCreate(LoginRequiredMixin, CreateView):
	form_class = AuthorForm
	success_url = reverse_lazy('news:list_authors')
	template_name = 'author/create_update.html'


class AuthorUpdate(LoginRequiredMixin, UpdateView):
	form_class = AuthorForm
	model = Author
	success_url = reverse_lazy('news:list_authors')
	template_name = 'author/create_update.html'


class AuthorDelete(LoginRequiredMixin, DeleteView):
	model = Author
	template_name = 'author/delete.html'
	success_url = reverse_lazy('news:list_authors')

src/apps/news/views/category.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

# Models
from apps.news.models import Category

# Form
from apps.news.forms import CategoryForm


class CategoryList(LoginRequiredMixin, ListView):
	context_object_name = 'categories'
	queryset = Category.objects.all()
	template_name = 'category/list.html'


class CategoryCreate(LoginRequiredMixin, CreateView):
	form_class = CategoryForm
	success_url = reverse_lazy('news:list_categories')
	template_name = 'category/create_update.html'


class CategoryUpdate(LoginRequiredMixin, UpdateView):
	form_class = CategoryForm
	model = Category
	success_url = reverse_lazy('news:list_categories')
	template_name = 'category/create_update.html'


class CategoryDelete(LoginRequiredMixin, DeleteView):
	model = Category
	template_name = 'category/delete.html'
	success_url = reverse_lazy('news:list_categories')

src/apps/news/views/news.py
import datetime

# Django
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import DeletionMixin

# Models
from apps.news.models import News, Gallery

# Form
from apps.news.forms import NewsForm, NewsUpdateForm


class NewsDetail(DetailView):
	model = News
	template_name = 'news/detail.html'


class NewsPnlList(LoginRequiredMixin, ListView):
	context_object_name = 'news'
	queryset = News.objects.filter(published=True).order_by('-date_published')
	template_name = 'news/admin_list.html'
	login_url = reverse_lazy('user:login')
	permission_required = "news.add_news"
	paginate_by = 10

	def get_context_data(self, **kwargs):
		context = super(NewsPnlList, self).get_context_data(**kwargs)
		context['news_inactive'] = News.objects.filter(published=False, is_task=False).order_by('-date_published')
		context['news_tasks'] = News.objects.filter(published=False, is_task=True).order_by('-date_published')
		context['total'] = News.objects.filter(published=True).order_by('-date_published').count()
		return context


class NewsCreate(LoginRequiredMixin, CreateView):
	form_class = NewsForm
	success_url = reverse_lazy('news:admin_news_list')
	template_name = 'news/create.html'
	login_url = reverse_lazy('user:login')
	permission_required = "news.add_news"

	def form_valid(self, form):
		self.object = form.save()
		self.object.date_published = datetime.datetime.now()
		images = self.request.FILES.getlist('images')
		for image in images:
			Gallery.objects.create(image=image, news=self.object)
		cover = self.object.gallery.first()
		self.object.cover = cover.image
		return super(NewsCreate, self).form_valid(form)


class NewsUpdate(LoginRequiredMixin, UpdateView):
	form_class = NewsUpdateForm
	model = News
	success_url = reverse_lazy('news:admin_news_list')
	template_name = 'news/update.html'
	login_url = reverse_lazy('user:login')
	permission_required = "news.change_news"

	def form_valid(self, form):
		self.object = form.save()
		images = self.request.FILES.getlist('images')
		for image in images:
			Gallery.objects.create(image=image, news=self.object)
		return super(NewsUpdate, self).form_valid(form)

	def get_context_data(self, **kwargs):
		context = super(NewsUpdate, self).get_context_data(**kwargs)
		images = Gallery.objects.filter(news=self.object)
		cover = images.first()
		self.object.cover = cover.image
		self.object.save()
		context['is_published'] = self.object.published
		context['gallery'] = images
		context['slug_news'] = self.object.slug
		return context


class NewsDelete(LoginRequiredMixin, DeleteView):
	model = News
	template_name = 'news/delete.html'
	success_url = reverse_lazy('news:admin_news_list')


class ImageDelete(DeletionMixin, SingleObjectMixin, View):
	login_url = reverse_lazy('user:login')
	model = Gallery
	permission_required = "news.delete_news"
	pk_url_kwarg = "pk"

	def get(self, *args, **kwargs):
		return self.delete(*args, **kwargs)

	def get_success_url(self):
		return reverse_lazy('news:update_news', kwargs={'slug':self.kwargs.get('slug')})

src/apps/news/templates/news/admin_list.html
{% extends "base.html" %}

{# {% load normalize_timesince %}  #}

{% block title %}Panel de Noticias{% endblock title %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="panel matchHeight">
      {% if news_tasks %}
      <div class="pnl__hdr">
        <p class="pnl__hdr__info">Tienes {{ news_tasks.count }} noticias programada</p>
      </div>
      <div class="pnl__table">
        <table class="tbl__rd__gral">
          <thead>
            <tr>
              <th>Noticias</th>
              <th>Autor</th>              
              <th colspan="2">Fecha programada</th>
            </tr>
          </thead>
          <tbody>
          {% for new in news_tasks %}            
            <tr>
              <td class="organisation__name">{{ new.title }}</td>
              <td class="organisation__author">{{ new.author }}</td>              
              <td class="organisation__tasks">{{ new.date_task|date:"D, d M Y" }}, {{ new.hour_task|time:"H:i" }}</td>
              <td class="actions__gral_one"><a href="{% url 'news:edit' new.slug %}" class="tbl__actions">Editar</a> | 
              <a href="{% url 'news:delete' new.pk %}" class="tbl__actions">Eliminar</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>              
      {% endif %}

      {% if news_inactive %}
      <div class="pnl__hdr">
        <p class="pnl__hdr__info">Tienes {{ news_inactive.count }} noticias no publicadas</p>
      </div>
      <div class="pnl__table">
        <table class="tbl__rd__gral">
          <thead>
            <tr>
              <th>Noticias</th>
              <th colspan="2">Autor</th>
            </tr>
          </thead>
          <tbody>
          {% for new in news_inactive %}            
            <tr>
              <td class="organisation__name">{{ new.title }}</td>
              <td class="organisation__author">{{ new.author }}</td>              
              <td class="actions__gral_one"><a href="{% url 'news:edit' new.slug %}" class="tbl__actions">Editar</a> | 
              <a href="{% url 'news:delete' new.pk %}" class="tbl__actions">Eliminar</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>        
      {% endif %}

      <div class="pnl__hdr">
        <p class="pnl__hdr__info">Tienes {{ total }} noticias publicadas</p>
        <p class="pnl__hdr__btn"><a href="{% url 'news:create_news' %}" class="btn">Nueva Nota</a></p>
      </div>
      <div class="pnl__table">
        <table class="tbl__rd__gral">
          <thead>
            <tr>
              <th>Hace</th>
              <th>Noticias</th>
              <th>Autor</th>
              <th>Vistas</th>
              <th colspan="2">Accion</th>
            </tr>
          </thead>
          <tbody>
          {% for news_obj in news %}            
            <tr>
              {# <td class="organisation__since" title="{{ news_obj.date_published }}">{{ news_obj.date_published|timesince|nrz:',' }}</td> #}
              <td class="organisation__since" title="{{ news_obj.date_published }}">{{ news_obj.date_published }}</td>
              <td class="organisation__name">{{ news_obj.title }}</td>
              <td class="organisation__author">{{ news_obj.author }}</td>
              <td class="organisation__views brd__last">{{ news_obj.views }}</td>
              <td class="actions">
                <a href="{% url 'news:update_news' news_obj.slug %}" class="tbl__actions">Editar</a> |
                <a href="{% url 'news:delete_news' news_obj.pk %}" class="tbl__actions">Eliminar</a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      {% if is_paginated %}
      {% include '_layouts/pagination.html' %}
      {% endif %}
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main>
{% endblock content %}

src/apps/news/templates/news/create.html
{% extends "base.html" %}

{% block title %}Nueva Noticia{% endblock title %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="gral__forms matchHeight">
      <h1>Administrar Noticia</h1>
      {{ form.media }}
      <form method="post" class="form__gral" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="field">
          {{ form.title.label_tag }}
          {{ form.title }}
          {{ form.title.errors }}
        </div>
        <div class="field">
          <label for="id_body">Contenido de la noticia:</label>
          {{ form.body }}
          {{ form.body.errors }}
        </div>
        <div class="field_2 pdn--lft">
          {{ form.author.label_tag }}
          {{ form.author }}
          {{ form.author.errors }}
        </div>
        <div class="field_2 pdn--rgh">
          {{ form.category.label_tag }}
          {{ form.category }}
          {{ form.category.errors }}
        </div>
        <div class="field_2 pdn--lft">
          {{ form.images.label_tag }}
          {{ form.images }}
          {{ form.images.errors }}
        </div>
        <div class="field_2 pdn--rgh">
          {{ form.video.label_tag }}
          {{ form.video }}
          {{ form.video.errors }}
        </div>
        {% if not is_published %}
        <div class="field">
          {{ form.is_task.label_tag }}
          {{ form.is_task }}
          {{ form.is_task.errors }}
        </div>
        <div class="field_2 pdn--lft">
          {{ form.date_task.label_tag }}
          {{ form.date_task }}
          {{ form.date_task.errors }}
        </div>
        <div class="field_2 pdn--rgh">
          {{ form.hour_task.label_tag }}
          {{ form.hour_task }}
          {{ form.hour_task.errors }}
        </div>
        {% endif %}
        <div class="field">
          <button type="submit" class="btn">Guardar</button>
        </div>
      </form>
      <div class="form__note">
        <p class="form__note__p">( * ) Son campos obligatorios a llenar</p>
        <br><br><br><br><br><br><br><br><br><br>
      </div>
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main> 
{% endblock content %}

src/apps/news/templates/news/delete.html
{% extends "base.html" %}

{% load static %}

{% block title %}Eliminar noticia{% endblock title %}

{% block css %}
<link href="{% static 'css/noticias.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="gral__forms matchHeight">
      <h1>Eliminar la noticia</h1>
      <form method="post" class="form__gral">
        {% csrf_token %}
        <p>¿Estás seguro de que deseas eliminar la noticia "{{ object.name }}"?</p>
        <div class="field">
          <button type="submit" class="btn">Eliminar</button>
          <a href="{% url 'news:admin_news_list' %}" class="btn">Cancelar</a>
        </div>
      </form>
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main>
{% endblock %}

src/apps/news/templates/news/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}{{ news.title }} | Sensor Informativo{% endblock title %}

{% block organic %}
  <meta property="og:site_name" content="Sensor Informativo: Su radar informativo"/>
  <meta property="og:title" content="{{ news.title }}" />
  <meta property="og:url" content="{% url 'news:detail_news' news.slug %}" />
  <meta property="og:description" content="{{ news.body|safe|striptags }}" />
  <meta property="og:type" content="article" />
  <meta property="og:locale" content="es_MX" />
{% if news.name_img %}
  <meta property="og:image" content="/media/wimg/{{ news.name_img }}">
  <meta property="og:image:url" content="/media/wimg/{{ news.name_img }}">
  <meta property="og:image:secure_url" content="/media/wimg/{{ news.name_img }}">
{% else %}
  <meta property="og:image" content="{{ news.gallery.all.0.image.url }}">
  <meta property="og:image:url" content="{{ news.gallery.all.0.image.url }}">
  <meta property="og:image:secure_url" content="{{ news.gallery.all.0.image.url }}">
{% endif %}
  <meta property="article:author" content="https://www.facebook.com/SensorInformativo" />
  <meta property="article:publisher" content="https://www.facebook.com/SensorInformativo" />
  <meta property="fb:app_id" content="1179482135399214" />
{% endblock organic %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/PhotoSwipe/photoswipe.css' %}">
  <link rel="stylesheet" href="{% static 'css/PhotoSwipe/default-skin.css' %}">
  <link rel="stylesheet" href="{% static 'css/imperavi.com/redactor.css' %}" />
{% endblock css %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <article class="new__dtl matchHeight">
      <header class="new__header">
        <div class="new__hdr__title">
          <h1 class="new__title">{{ news.title }}</h1>
          <p class="new__category"><a href="#">{{ news.category }}</a></p>
        </div>
        <div class="new__hdr__author_date">
          <p class="new__author">Por: {{ news.author }}</p>
          <p class="new__date">{{ news.date_published }}</p>
        </div>
      </header>
      <section class="new__media">
      {% if news.video %}
        <div class="video__wrapper">
          <iframe width="560" height="315" src="http://www.youtube.com/embed/{{news.embed}}" frameborder="0" allowfullscreen></iframe>
        </div>
      {% else %}
        <img src="{{ news.cover.url }}" alt="{{ news.slug }}">
      {% endif %}
      </section>
      <section class="new__body" id="new__body">
        {{ news.body|safe }}
      </section>
      <div class="sponsor" id="sponsor" style="width: 100%;">
        <div id="hdr__sponsor">
          {% for s in sponsor_one %}
          <div>
            <a href="#" target="_blank"></a>
          </div>
          {% endfor %}
        </div>
      </div>
      <section>
        <div class="gral__dtl">
          <h2>Imagenes</h2>
        </div>
        <div id="demo-test-gallery" class="demo-gallery">
          {% for i in news.gallery.all %}
          <img src="{{ n.image }}" alt="{{ n.slug }}"></a>
          {% endfor %}
        </div>
      </section>
      <section class="new__footer">
        <br>
        <hr>
        <br>
        <p class="new_share">Comparte esta nota</p>
        <br>
        <div class="sharethis-inline-share-buttons"></div>
      </section>
      <section class="new__comments">
        <h2 class="new__cmt__title">Comentarios</h2>
        {% if user.is_authenticated %}
        <div class="new__cmt__form">
          {% if user.avatar %}
            <div class="new__cmt__image"><img src="{{user.avatar}}" alt="Photo: {{user.username}}"/></div>
          {% else %}
            <div class="new__cmt__image"><div class="no__image"><p>{{user.username}}</p></div></div>
          {% endif %}
          <form class="form__comments" id="comment-form" method="post">
            {% csrf_token %}
            <div>
              <textarea name="comment" id="comment" placeholder="Agregue su comentario" required></textarea>
            </div>
            <input type="hidden" name="news_id" value="{{ news.id }}">
            <div>
              <button class="btn">Comentar</button>
            </div>
          </form>
        </div>
        {% else %}
        <div class="new__cmt__form">
          <h2 class="cmt__title"><a href="{% url 'user:login' %}?next={{ request.path }}">Inicia Sesión</a></h2>
          <p class="cmt__title__aux">O</p>
          <hr>
        </div>
        {% endif %}
        <section class="list__comments" id="list-comments">
        {% for c in news.comments.all  %}
          <section class="user__comment">
          {% if c.user.avatar %}
            <div class="new__cmt__image"><img src="{{c.user.avatar}}" alt="Photo: {{c.user.username}}"/></div>
          {% else %}
            <div class="new__cmt__image"><div class="no__image"><p>{{c.user.first_name}}</p></div></div>
          {% endif %}
            <div class="user__cmt">
            <div class="user__cmt__header">
              <p class="user__cmt__name">{{ c.user.first_name }} {{ c.user.last_name }}</p>
              <p class="user__cmt__date">Hace: {{ c.created|timesince }}</p>
            </div>
              <p class="user__cmt__comment">{{ c.comment|safe }}</p>
            </div>
          </section>
        {% endfor %}
        </section>
      </section>
    </article>
    {% include '_layouts/sponsors.html' %}
  </div>
</main>
{% endblock content %}

src/apps/news/templates/news/update.html
{% extends "base.html" %}

{% block title %}Actualizar Noticia{% endblock title %}

{% block content %}
<main class="news__dtl">
  <div class="container">
    <section class="gral__forms matchHeight">
      <h1>Administrar Noticia</h1>
      {{ form.media }}
      <form method="post" class="form__gral" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="field">
          {{ form.title.label_tag }}
          {{ form.title }}
          {{ form.title.errors }}
        </div>
        <div class="field">
          <label for="id_body">Contenido de la noticia:</label>
          {{ form.body }}
          {{ form.body.errors }}
        </div>
        <div class="field_2 pdn--lft">
          {{ form.author.label_tag }}
          {{ form.author }}
          {{ form.author.errors }}
        </div>
        <div class="field_2 pdn--rgh">
          {{ form.category.label_tag }}
          {{ form.category }}
          {{ form.category.errors }}
        </div>
        <div class="field_2 pdn--lft">
          {{ form.video.label_tag }}
          {{ form.video }}
          {{ form.video.errors }}          
        </div>
        <div class="field">
          {{ form.images.label_tag }}
          {{ form.images }}
          {{ form.images.errors }}
        </div>
        {% if gallery %}
        <div id="demo-test-gallery" class="demo-gallery">
        <br>
        <br>
          {% for image in gallery %}
            <div  style="float:left; margin-right:8px; text-align:center;">              
            <img src="{{ image.image.url }}" alt="Imagen" class="gallery__style" width="195" height="115">
            {% if gallery|length > 1 %}
              <p><a href="{% url 'news:delete_image' image.pk slug_news %}" style="color:red;">Eliminar</a></p>              
            {% endif %}
            </div>
          {% endfor %}
        </div>          
        {% endif %}
        {% if not is_published %}
        <div class="field">
          {{ form.is_task.label_tag }}
          {{ form.is_task }}
          {{ form.is_task.errors }}
        </div>
        <div class="field_2 pdn--lft">
          {{ form.date_task.label_tag }}
          {{ form.date_task }}
          {{ form.date_task.errors }}
        </div>
        <div class="field_2 pdn--rgh">
          {{ form.hour_task.label_tag }}
          {{ form.hour_task }}
          {{ form.hour_task.errors }}
        </div>
        <div class="field">
          {{ form.published.label_tag }}
          {{ form.published }}
          {{ form.published.errors }}
        </div>
        {% endif %}
        <div class="field">
          <button type="submit" class="btn">Actualizar</button>
        </div>
      </form>
      <div class="form__note">
        <p class="form__note__p">( * ) Son campos obligatorios a llenar</p>
      </div>
    </section>
    {% include '_layouts/pnl_sponsors.html' %}
  </div>
</main> 
{% endblock content %}